version: '2'
services:
  instant-whales:
    build: .
    ports:
      - 8080:8080
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      INSTANT_WHALES_RELEASE_MODE: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    read_only: true
